spring:
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: ${OPEN_ID_API_BASE_URI:http://localhost:5000/o}

idam:
  s2s-auth:
    totp_secret: ${AM_JUDICIAL_BOOKING_SERVICE_SECRET:AAAAAAAAAAAAAAAA}
    microservice: am_judicial_booking_service
    url: ${IDAM_S2S_URL:http://localhost:4502}
  api.url: ${IDAM_USER_URL:http://localhost:5000}
  client:
    id: ${JUDICIAL_BOOKING_IDAM_CLIENT_ID:am_docker}
    secret: ${JUDICIAL_BOOKING_IDAM_CLIENT_SECRET:am_docker_secret}
    redirect_uri: ${JUDICIAL_BOOKING_IDAM_REDIRECT_URI:http://localhost:4096/oauth2redirect}

scope-name: openid profile roles manage-user create-user search-user
oauth2-client-secret: ${OAUTH2_CLIENT_SECRET:}
test.user.password: test